site_name: Zerker
site_url: https://lumbridgecrow.github.io
theme:
  name: material
  custom_dir: overrides
  font: 
    text: Merriweather Sans
  palette:
    scheme: slate
    primary: black
    accent: lime
  features:
    - navigation.footer
    - content.code.copy
    - content.tabs.link
    - navigation.indexes
    - navigation.sections
    - navigation.instant.prefetch
    - navigation.path
    - navigation.top

extra_css:
  - stylesheets/extra.css
  - styles/disable-search.css

extra_javascript:
  - javascripts/extra.js

nav:
  - Home: index.md
  - FAQ: faq.md
  - Check Lists: 
    - Quick Zerker Quest List: qzql.md
    - Completionist Zerker Quest List: cql.md
    - Achievements Check List: acl.md
  - Training:
    - Melee: meleetraining.md
    - Ranged: rangedtraining.md
    - Magic: magetraining.md

extra:
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/LumbridgeCrow
      name: Lumbridge Crow Twitter/X
    - icon: fontawesome/brands/youtube
      link: https:/youtube.com/@lumbridgecrow
      name: Lumbridge Crow YouTube

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides\.icons
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      